2021-03-02 21:48:39,128 ERROR: Exception on /reset_password_request [POST] [in /Users/ivankhokhlov/Flask/microblog/venv/lib/python3.9/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/ivankhokhlov/Flask/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/ivankhokhlov/Flask/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/ivankhokhlov/Flask/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/ivankhokhlov/Flask/microblog/venv/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/ivankhokhlov/Flask/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/ivankhokhlov/Flask/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/ivankhokhlov/Flask/microblog/app/routes.py", line 181, in reset_password_request
    send_password_reset_email(user)
  File "/Users/ivankhokhlov/Flask/microblog/app/email.py", line 13, in send_password_reset_email
    send_email('[Microblog] Reset Your Password',
  File "/Users/ivankhokhlov/Flask/microblog/app/email.py", line 9, in send_email
    mail.send(msg)
  File "/Users/ivankhokhlov/Flask/microblog/venv/lib/python3.9/site-packages/flask_mail.py", line 491, in send
    with self.connect() as connection:
  File "/Users/ivankhokhlov/Flask/microblog/venv/lib/python3.9/site-packages/flask_mail.py", line 144, in __enter__
    self.host = self.configure_host()
  File "/Users/ivankhokhlov/Flask/microblog/venv/lib/python3.9/site-packages/flask_mail.py", line 156, in configure_host
    host = smtplib.SMTP_SSL(self.mail.server, self.mail.port)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/smtplib.py", line 1034, in __init__
    SMTP.__init__(self, host, port, local_hostname, timeout,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/smtplib.py", line 253, in __init__
    (code, msg) = self.connect(host, port)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/smtplib.py", line 1041, in _get_socket
    new_socket = self.context.wrap_socket(new_socket,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1123)
2021-03-02 21:51:21,026 INFO: Microblog startup [in /Users/ivankhokhlov/Flask/microblog/app/__init__.py:51]
2021-03-02 21:52:48,177 ERROR: Exception on /reset_password_request [POST] [in /Users/ivankhokhlov/Flask/microblog/venv/lib/python3.9/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/ivankhokhlov/Flask/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/ivankhokhlov/Flask/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/ivankhokhlov/Flask/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/ivankhokhlov/Flask/microblog/venv/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/ivankhokhlov/Flask/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/ivankhokhlov/Flask/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/ivankhokhlov/Flask/microblog/app/routes.py", line 181, in reset_password_request
    send_password_reset_email(user)
  File "/Users/ivankhokhlov/Flask/microblog/app/email.py", line 13, in send_password_reset_email
    send_email('[Microblog] Reset Your Password',
  File "/Users/ivankhokhlov/Flask/microblog/app/email.py", line 9, in send_email
    mail.send(msg)
  File "/Users/ivankhokhlov/Flask/microblog/venv/lib/python3.9/site-packages/flask_mail.py", line 491, in send
    with self.connect() as connection:
  File "/Users/ivankhokhlov/Flask/microblog/venv/lib/python3.9/site-packages/flask_mail.py", line 144, in __enter__
    self.host = self.configure_host()
  File "/Users/ivankhokhlov/Flask/microblog/venv/lib/python3.9/site-packages/flask_mail.py", line 156, in configure_host
    host = smtplib.SMTP_SSL(self.mail.server, self.mail.port)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/smtplib.py", line 1034, in __init__
    SMTP.__init__(self, host, port, local_hostname, timeout,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/smtplib.py", line 253, in __init__
    (code, msg) = self.connect(host, port)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/smtplib.py", line 1040, in _get_socket
    new_socket = super()._get_socket(host, port, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/socket.py", line 843, in create_connection
    raise err
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/socket.py", line 831, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 60] Operation timed out
2021-03-02 21:53:22,932 ERROR: Exception on /reset_password_request [POST] [in /Users/ivankhokhlov/Flask/microblog/venv/lib/python3.9/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/ivankhokhlov/Flask/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/ivankhokhlov/Flask/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/ivankhokhlov/Flask/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/ivankhokhlov/Flask/microblog/venv/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/ivankhokhlov/Flask/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/ivankhokhlov/Flask/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/ivankhokhlov/Flask/microblog/app/routes.py", line 181, in reset_password_request
    send_password_reset_email(user)
  File "/Users/ivankhokhlov/Flask/microblog/app/email.py", line 13, in send_password_reset_email
    send_email('[Microblog] Reset Your Password',
  File "/Users/ivankhokhlov/Flask/microblog/app/email.py", line 9, in send_email
    mail.send(msg)
  File "/Users/ivankhokhlov/Flask/microblog/venv/lib/python3.9/site-packages/flask_mail.py", line 491, in send
    with self.connect() as connection:
  File "/Users/ivankhokhlov/Flask/microblog/venv/lib/python3.9/site-packages/flask_mail.py", line 144, in __enter__
    self.host = self.configure_host()
  File "/Users/ivankhokhlov/Flask/microblog/venv/lib/python3.9/site-packages/flask_mail.py", line 156, in configure_host
    host = smtplib.SMTP_SSL(self.mail.server, self.mail.port)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/smtplib.py", line 1034, in __init__
    SMTP.__init__(self, host, port, local_hostname, timeout,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/smtplib.py", line 253, in __init__
    (code, msg) = self.connect(host, port)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/smtplib.py", line 1041, in _get_socket
    new_socket = self.context.wrap_socket(new_socket,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1123)
2021-03-02 21:54:00,073 INFO: Microblog startup [in /Users/ivankhokhlov/Flask/microblog/app/__init__.py:51]
